# .rubocop.yml

inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.1.3
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'app/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'spec/**/*'

# Disable documentation requirement
Documentation:
  Enabled: false

Layout/LineLength:
  Max: 200


# Allow longer methods
Metrics/MethodLength:
  Max: 250

# Disable block length check
Metrics/BlockLength:
  Enabled: false
  

Layout/Documentation:
  Enabled: false

