# .rubocop.yml

# Hereda configuraciones de la gema base de RuboCop
inherit_from:
  - .rubocop_todo.yml

# Reglas generales para todos los policías
AllCops:
  TargetRubyVersion: 3.1.3 # Ajusta según tu versión de Ruby
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'node_modules/**/*'

# Desactiva la necesidad de documentación para cada clase y módulo
Documentation:
  Enabled: false

# Ajusta la longitud máxima de las líneas
Metrics/LineLength:
  Max: 200

# Permite métodos más largos de lo usual
Metrics/MethodLength:
  Max: 35

# Permite bloques más largos de lo usual
Metrics/BlockLength:
  Enabled: false
