name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: Testing_db_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.3'

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run RuboCop
      run: bundle exec rubocop

    - name: Check PostgreSQL Service
      run: |
        echo "Checking PostgreSQL service availability..."
        nc -zv postgres 5432 || true  # Using || true to ensure the step does not fail and allows further commands to execute
        echo "Attempting to connect to PostgreSQL..."
        PGPASSWORD=$DB_PASSWORD psql -h postgres -U $DB_USER -d $POSTGES_DB -c 'SELECT version();'
      shell: /usr/bin/bash -e {0}
      env:
        RAILS_ENV: test
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_HOST: postgres
        DATABASE_URL: postgres://postgres:postgres@postgres:5432/Testing_db_test
        SELENIUM_DRIVER_URL: http://localhost:9515
    

    - name: Run tests
      run: bundle exec rspec

    env:
      RAILS_ENV: test
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres  # Set to the service name
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/Testing_db_test
      SELENIUM_DRIVER_URL: http://localhost:9515
