
  # This workflow uses actions that are not certified by GitHub.  They are
  # provided by a third-party and are governed by separate terms of service,
  # privacy policy, and support documentation.
  #
  # This workflow will install a prebuilt Ruby version, install dependencies, and
  # run tests and linters.
  name: "Ruby on Rails CI"
  on:
    pull_request:
      branches: ["main"]
  jobs:
    test:
      runs-on: ubuntu-latest
      services:
        postgres:
          image: postgres
          ports:
            - "5432:5432"
          env:
            POSTGRES_DB: testing_db_test
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
      env:
        RAILS_ENV: test
        DATABASE_URL: "postgres://postgres:password@localhost:5432/testing_db_test"
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Set up Chrome
          run: |
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
  
        # Add or replace dependency steps here
        - name: Install Ruby and gems
          uses: ruby/setup-ruby@v1
          with:
            bundler-cache: true
  
        - name: Install Chromedriver
          run: |
            sudo apt-get install -y chromium-chromedriver
  
        # Add or replace database setup steps here
        - name: Set up database schema
          run: bundle exec rails db:schema:load
  
        # Add or replace test runners here
        - name: Run rspec tests
          run: bundle exec rspec
  
        - name: Store coverage
          uses: actions/upload-artifact@v3
          with:
            name: coverage_report
            path: coverage/
  
    rubocop:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        # Add or replace dependency steps here
        - name: Install Ruby and gems
          uses: ruby/setup-ruby@v1
          with:
            bundler-cache: true
  
        - name: Run Rubocop with auto-correction
          run: bundle exec rubocop --parallel --auto-correct