name: "ci"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: testing_db_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:password@localhost:5432/testing_db_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: '3.1.3'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable chromium-chromedriver
          gem install bundler
          bundle install

      - name: Set up database schema
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load

      - name: Run rspec tests
        run: bundle exec rspec

      - name: Store coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage_report
          path: coverage/

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: '3.1.3'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Rubocop with auto-correction
        run: bundle exec rubocop --auto-correct
